#####
# Makefile for PumpMinion Arduino sketch
# Author: Ron Smith
# Created: 2014-10-18
#####

ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr

BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0

#BOARD_TAG    = nano328
#MONITOR_PORT = /dev/ttyUSB0

# root project directory where libraries directory is located
ARDUINO_SKETCHBOOK=/home/ron/Projects/master-minion

ARDUINO_LIBS = RCSwitch

include $(ARDUINO_DIR)/Arduino.mk



